### ISSUE TITLE
/element by xpath is passing an incorrect xpath 

### ISSUE THREAD

**Issue by sglebs** [andreptb/fitnesse-selenium-slim#1]
Hi @andreptb 

I run this:

```
| ensure    | type  |33*2=| in | xpath=/AXWindow/AXStaticText[1]|
```

You pass me this:

```
POST /wd/hub/session/1435162114401/element HTTP/1.1
Content-Type: application/json; charset=utf-8
Content-Length: 59
Host: localhost:5555
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5 (Java/1.8.0_40)
Accept-Encoding: gzip,deflate

{"using":"xpath","value":"xpath=/AXWindow/AXStaticText[1]"}
```

But Xebium and others use this:

```
POST /wd/hub/session/1435162366809/element HTTP/1.1
Content-Type: application/json; charset=utf-8
Content-Length: 45
Host: localhost:5555
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.3.5 (java 1.5)
Accept-Encoding: gzip,deflate

{"using":"xpath","value":"/AXWindow/AXGroup"}
```

In other words, when the strategy is path, I believe you need to remove the "xpath=" from the actual value. This probably applies to others like "id=" etc.

**Comment by andrealbinop** [comment]
Hi @sglebs 
The problem only happened with xpath selector when **xpath=** prefix is used. Fixed and created a [regression test](https://github.com/andreptb/fitnesse-selenium-slim/blob/selenium_script_table/fitnesse/FitNesseRoot/FitNesseSeleniumSlim/SeleniumFixtureTests/TypeTests/ByXPathSelectorTest/content.txt).
