### ISSUE TITLE
close window?

### ISSUE THREAD

**Issue by sglebs** [andreptb/fitnesse-selenium-slim#11]
You have selectWindow and openWIndow. I was expecting to find a closeWindow but it is in fact called close. Look at http://localhost:6060/FitNesseSeleniumSlim.SeleniumFixtureTests.WindowSelectTests.ByTitleTest

I think it would be more uniform to call it closeWindow, no? Ot at least have close (current browser?) and closeWindow (just current window).

**Comment by andrealbinop** [comment]
**close** command won't do for you? Take a look at [this](../blob/master/fitnesse/FitNesseRoot/FitNesseSeleniumSlim/SeleniumFixtureTests/WindowSelectTests/ByIdTest/content.txt) test (line 9).

**Comment by andrealbinop** [comment]
@sglebs 

I tried to implement the fixture as "close" (no pun intended) as **[SeleniumIDE](http://www.seleniumhq.org/docs/02_selenium_ide.jsp)** as possible, as can be seen below:
- **[selectWindow](http://release.seleniumhq.org/selenium-core/1.0.1/reference.html#selectWindow)**
- **[close](http://release.seleniumhq.org/selenium-core/1.0.1/reference.html#close)**
- **[openWindow](http://release.seleniumhq.org/selenium-core/1.0.1/reference.html#openWindow)**

With that said, I'm keeping that way. Anyway, thank you for pointing it out.
