### ISSUE TITLE
Firefox still opens download dialog for non-standard mime type 

### ISSUE THREAD

**Issue by sglebs** [andreptb/fitnesse-selenium-slim#26]
Version 0.8.0 prevents Firefox from opening the dialog asking for user download prefs, and this is nice. However, that is not the case for a non-standard mime type. It still opens the native dialog.

Is it possible to add an API so that testers can, from the fitness table, register more mime types that the fixture should also ignore? a CSV string is fine, for example.

Thanks!

**Comment by sglebs** [comment]
A little correction. The mime type seems to be PDF. But the href does not end with .pdf. Could that be it? The back-end dev said this is how they do it in the back-end:

```
public static void setInResponse(final HttpServletResponse response, final String fileName,
final byte[] file)
{
response.setContentType("application/pdf");
response.setContentLength(file.length);
response.addHeader("Content-Type", "application/pdf" + "; charset=ISO-8859-1");
setFileInHeader(response, fileName);
try
{
response.getOutputStream().write(file);
response.getOutputStream().flush();
}
catch (IOException e)
{
e.printStackTrace();
}
}

private static void setFileInHeader(final HttpServletResponse response, final String fileName)
{
if (fileName != null)
{
String file = fileName;
final int idx = fileName.indexOf(';') + 1;
if (idx > 0)
{
file = fileName.substring(idx);
}
if(!file.contains(".pdf")){
file += ".pdf";
}

response.addHeader("Content-Disposition", "ATTACHMENT; filename=\"" + file + "\"");
}
}
```

**Comment by andrealbinop** [comment]
As demonstrated [here (line 28)](https://github.com/andreptb/fitnesse-selenium-slim/blob/master/src/main/java/com/github/andreptb/fitnesse/selenium/WebDriverCapabilitiesHelper.java), **application/pdf** content type is already configured to trigger download without dialog. 

Furthermore, you can add custom content types when starting Firefox browser with the following:

```
| start browser | ... | with | ... | and preferences | browser.helperApps.neverAsk.saveToDisk='<custom content types>' |
```

**Comment by sglebs** [comment]
The tester tried this:

```
| start browser | @browser | with preferences |  browser.helperApps.neverAsk.saveToDisk='application/pdf;charset=ISO-8859-1' |
```

and Firefox still opened the download dialog.

Ideas?

**Comment by andrealbinop** [comment]
Can you try running [this test](https://github.com/andreptb/fitnesse-selenium-slim/blob/master/fitnesse/FitNesseRoot/FitNesseSeleniumSlim/SeleniumFixtureTests/ManualTests/DownloadFileTest/content.txt) and see if it works?

**Comment by andrealbinop** [comment]
@sglebs,

Are you still having problems?
