### ISSUE TITLE
why clear before keystrokes?

### ISSUE THREAD

**Issue by sglebs** [andreptb/fitnesse-selenium-slim#3]
Hi @andreptb 

I am trying to send text to an element (in my case a static field in a native GUI element with my custom MacOS web driver  - it could be a SPAN on an HTML page) but I have noticed that your fixture insists on calling CLEAR first. The other web-drivers I have used (Xebium, hsac) do not do this.

Is it possible to at least turn this off from the table? setAutoClearBeforeTyping(bool) for example?

Thanks!

**Comment by andrealbinop** [comment]
Hi @sglebs 
According to Selenium reference documentation the [type](http://release.seleniumhq.org/selenium-core/1.0.1/reference.html#type) command should **set** the value, so the content should indeed be replaced. I've found a [few](http://stackoverflow.com/questions/3249583/selenium-webdriver-i-want-to-overwrite-value-in-field-instead-of-appending-to-i) different ways to do it, and the most compatible way seemed to be:

``` java
element.clear();
element.sendKeys("Some text here");
```

So if you need to append some text without clearing it first you can use the **send keys** action, check [here](https://github.com/andreptb/fitnesse-selenium-slim/blob/selenium_script_table/fitnesse/FitNesseRoot/FitNesseSeleniumSlim/SeleniumFixtureTests/SendKeysTests/ByLogicNameTest/content.txt) to see how it works.
