### ISSUE TITLE
Problem running tests on 2 different computers / resolutions

### ISSUE THREAD

**Issue by sglebs** [andreptb/fitnesse-selenium-slim#32]
We are testing an app on a desktop PC with screen resolution of 1600x900 and use the window maximize as per ticket #19. The tests run fine. However, when running on a laptop with screen resolution with 1366x768 many tests fail when trying to execute "click id=uf". The HTML element was loaded but required scrolling to bring it to the visible browser pane. What do you suggest? I think I recall Xebium scrolling to view?

Did we miss anything?

Do we need to set a fixed screen resolution on SuiteSetUp? If so, how? There does not seem to be such an API, just for maximizing.

Thanks!

**Comment by sglebs** [comment]
Is there support to set a specific screen resolution?

**Comment by andrealbinop** [comment]
I've introduced **[set window size](http://andreptb.github.io/fitnesse-selenium-slim/apidocs/com/github/andreptb/fitnesse/SeleniumFixture.html#setWindowSize-java.lang.String-)** action to allow setting specific screen resolution. About scrolling maybe you can use [javascript](http://andreptb.github.io/fitnesse-selenium-slim/apidocs/com/github/andreptb/fitnesse/SeleniumFixture.html#runScript-java.lang.String-)  to [position the scroll](https://api.jquery.com/scrollTop/#scrollTop-value) to the desired portion of the page.
