### ISSUE TITLE
screenshots saved to the parent page?

### ISSUE THREAD

**Issue by sglebs** [andreptb/fitnesse-selenium-slim#4]
I run this test:

http://localhost:6060/FitNesseSeleniumSlim.SandBox.MacOsWebDriver.TestTheCalculatorWithClicksByButtonId

but the screenshot gets saved to:

http://localhost:6060/files/testResults/FitNesseSeleniumSlim.SandBox.MacOsWebDriver/screenshots/screenshot1109899880611272468.png

**Comment by andrealbinop** [comment]
Done!

**Comment by andrealbinop** [comment]
Unfortunatelly auto-detecting screenshot directory is not possible yet (see [README.md](README.md)). Leaving this issue opened until then.

**Comment by andrealbinop** [comment]
Seems [this](https://github.com/unclebob/fitnesse/pull/755) will take a looong time to be merged. I've decided to close this issue and reopen when a version of FitNesse with the aforementioned features is available.
