### ISSUE TITLE
Please support ${KEY_TAB}

### ISSUE THREAD

**Issue by sglebs** [andreptb/fitnesse-selenium-slim#6]
If I use this:

```
| send keys | !-${KEY_TAB}-! |
```

You are sending this literal: "${KEY_TAB}" instead of replacing it with a TAB.

Workaround: I have to use this:

```
| send keys | tab |
```

**Comment by andrealbinop** [comment]
Hi,
I've changed [SeleniumPluginFeatureFactory.java](src/main/java/com/github/andreptb/fitnesse/plugins/SeleniumPluginFeatureFactory.java) to register as system properties all selenium special keys so you can use ${KEY_TAB}. Take a look at [SendKeysTests](fitnesse/FitNesseRoot/FitNesseSeleniumSlim/SeleniumFixtureTests/SendKeysTests/content.txt) to see how it works.

Note that now this is the only way to use special keys, commands such as example below will print "tab" literally:

```
| send keys | tab |
```
