### ISSUE TITLE
how can I send the literal "tab"?

### ISSUE THREAD

**Issue by sglebs** [andreptb/fitnesse-selenium-slim#7]
If I use this:

```
| send keys | tab |
```

It is magically interpreted and replaced with a TAB. So, how can I send "tab" (without the quotes)?

**Comment by sglebs** [comment]
Maybe have a "sendSpecialKeys" and "sendLiteralKeys"? AutoIt follows this approach.

**Comment by andreptb** [comment]
What situation you need to type "tab" text literally? Note that special keys will only be "magically interpreted" if it's used alone. In the command below "tab" is interpreted as literal:

```
| send keys | sometext tab |
```

**Comment by andrealbinop** [comment]
Take a look at #6, "magical intepretation" of special keys were removed. To use special keys just use ${KEY_TAB}
